### ISSUE TITLE
Use event based orderbook

### ISSUE THREAD

**Issue by josojo** [gnosis/dex-price-estimator#19]
While this is not an issue right now, it might become one in the future.

Since we are pulling the orderbook every 10 seconds, this consumes quite some node resources. With a further increase in the orderbook size, this might end up in a potential issue.

One solution could be the order book fetching via events between batches.

More background:
https://gnosisinc.slack.com/archives/CU37HR35W/p1587028832005300

**Comment by fleupold** [comment]
Note, that you can customize the poll frequency with and env variable `POLL_FREQUENCY=30000` would set it to 30s

**Comment by nlordell** [comment]
We should be able to integrate the event based orderbook from `dex-contracts` once gnosis/dex-contracts#717 gnosis/dex-contracts#718 gnosis/dex-contracts#719 gnosis/dex-contracts#720 are fixed.

**Comment by nlordell** [comment]
This has been fixed
