### ISSUE TITLE
USDC-WBTC not estimated correctly

### ISSUE THREAD

**Issue by josojo** [gnosis/dex-price-estimator#20]
Currently, the price estimation is infinity, while in the order book, we can see some liquidity

**Comment by fleupold** [comment]
Can you please provide the URL and response you were using? It works fine for me:

https://price-estimate-mainnet.dev.gnosisdev.com/api/v1/markets/11-4/estimated-buy-amount/100000000?atoms=true

> {"baseTokenId":"11","quoteTokenId":"4","buyAmountInBase":1435671.9478406978,"sellAmountInQuote":100000000}

Same for prod. Note that you are specifying the amount in quote token and USDC has 6 decimals.

**Comment by josojo** [comment]
It was just mesa.eth.link. But now it works :) 
Next time I will also add time and exact response... Maybe it happens only under heavier load.
