### ISSUE TITLE
Use wasm pricegraph for price estimation 

### ISSUE THREAD

**Issue by fleupold** [gnosis/dex-price-estimator#33]
Since price estimates are taking quite long these days (~2s) we should try to speed this up by using the wasm graph based implementation.

**Comment by nlordell** [comment]
This involves pulling in the [`@gnosis.pm/dex-pricegraph`](https://www.npmjs.com/package/@gnosis.pm/dex-pricegraph) package and then passing in the orderbook to the `Pricegraph`.

**Comment by e00E** [comment]
I have this implemented in the branch `wasm-pricegraph` but cannot test it yet. Nick is going to make another release of the pricegraph to fix a module import error at which point I'll continue.

**Comment by nlordell** [comment]
I released [@gnosis.pm/dex-pricegraph v0.0.1-alpha.2](https://www.npmjs.com/package/@gnosis.pm/dex-pricegraph) :rocket:
