### ISSUE TITLE
Return only the buyAmountInBase for price estimation

### ISSUE THREAD

**Issue by e00E** [gnosis/dex-price-estimator#43]
It doesn't make sense to include base, quote, sellAmountInQuote. They are all already known by the requester because they have to be passed in so there is no value in returning them again.

**Comment by fleupold** [comment]
This was discussed with @anxolin in the original [API design](https://github.com/gnosis/dex-price-estimator/pull/10). The main thought was to make it really clear what is what we include this information in a named json struct. 

This is also somewhat similar to the [kyber api](https://developer.kyber.network/docs/Trading/#buy-rate)

**Comment by e00E** [comment]
Because you have discussed it before and this was an intentional decision I see no reason to discuss it again or change it now. I do disagree but it is of low importance so I'll close the issue.
