### ISSUE TITLE
Make price estimation rounding tighter.

### ISSUE THREAD

**Issue by fleupold** [gnosis/dex-price-estimator#52]
Looking into other stablecoin swaps I noticed that spreads are extremely competitive. E.g., at the moment our price estimator offers 0.99690 USDC/DAI while [mStable](https://app.mstable.org/swap) offers marginally better 0.997.

However when actually doing a trade we end up achieving a better price of 0.9979.
While this is a great "surprise" for the user it would be nice if we could make our price estimation "tighter", as people might not even attempt to trade otherwise. At the moment we just add another 0.1% rounding buffer on top.

How exactly are we computing the rounding buffer for our solutions (@twalth3r @marcovc  @josojo) and what would be a good strategy to use in the price estimator?

**Comment by marcovc** [comment]
Just to point out that if this estimation is based on @nlordell 's algo then I believe that other factor than rounding may cause the error, specifically the fact that the uniform clearing price condition is relaxed.

**Comment by twalth3r** [comment]
The rounding buffer is currently determined individually for every order, depending on the price estimates of the tokens involved (which also reflects the number of decimals). The idea is that we might need more rounding buffer when small amounts of a very expensive token (e.g., GUSD) are traded. Here's the relevant code: https://github.com/gnosis/dex-solver/blob/master/src/opt/process/Rounding.py#L67-L90

**Comment by marcovc** [comment]
I believe the rounding buffer can be tightened. We discussed a few times we should do it eventually, but never really thought too much about it. At some point I was thinking that something along these lines could work: https://github.com/gnosis/dex-solver/pull/196#pullrequestreview-388084765 .

**Comment by fleupold** [comment]
Nice, it would be great if we can make the rounding deterministic as right now it seems to be based on information that the price estimator would not have. I'll try to setup a synchronous discussion about it.

**Comment by fleupold** [comment]
Closing this in favor of issue in the repo where this will actually be implemented: https://github.com/gnosis/dex-services/issues/970
